### ISSUE TITLE
Doubt in Page 42.

### ISSUE THREAD

**Issue by pranavchat14** [abhishekkrthakur/how-to-become-a-ds-in-30-days#1]
Line 42 on the page says    .  Should it rather not be 42? 

Please confirm.

P. S. -- Thank you so much for the book. It is enlightening and has helped me in understanding Creatio ex nihilo.
Abhishek Bhai OP

**Comment by abhishekkrthakur** [comment]
I'm sorry you faced this problem. Please open a PR to fix page 42. Please note that the PR must not modify the whole book and must pass all the tests 🤣
